'use client';

import Link from 'next/link';
import styles from './styles.module.css';

export default function JoinPage() {
  const roles = [
    {
      title: 'Developer',
      subtitle: 'Supervise AI-Generated Code',
      icon: '👨‍💻',
      emoji: '⚡',
      color: '#64A8FF',
      whatYouDo: [
        'Review code generated by Rafael (30 min)',
        'Deploy to Render/Vercel following step-by-step guides (1h)',
        'Test using Sofia\'s automated checklists (1h)',
        'Fix bugs with Rafael\'s guidance (30 min)',
      ],
      whatAIDoes: [
        'Emma finds jobs and writes proposals (2 min)',
        'Inna writes complete specifications (5 min AI time)',
        'Rafael generates 100% working code (2 min AI time)',
        'Sofia verifies all quality criteria (30s AI time)',
        'Maya handles all client communication (1 min AI time)',
      ],
      aiSupport: ['Rafael', 'Sofia', 'Maya'],
      earnings: '$90-97.50 per mission',
      missions: '10-12 missions/month',
      totalEarnings: '$900-1,170/month',
      ppp: '$4,500-5,850 purchasing power',
      skillsNeeded: [
        'Basic command line (cd, ls, git)',
        'Can follow deployment tutorials',
        'Willing to learn by doing',
        'No senior experience needed',
      ],
      timeCommitment: '25-30 hours/week',
    },
    {
      title: 'QA Tester',
      subtitle: 'Find Jobs + Test Deliverables',
      icon: '🔍',
      emoji: '✓',
      color: '#5CE27E',
      whatYouDo: [
        'Search Upwork for jobs (30 min/day)',
        'Paste jobs to Emma for analysis (2 min)',
        'Submit proposals written by Emma (5 min)',
        'Test deliverables before client sees them (2-3h per mission)',
      ],
      whatAIDoes: [
        'Emma analyzes job posts (30s per batch)',
        'Emma writes complete proposals (30s)',
        'Sofia generates test checklists (30s)',
        'Sofia runs automated tests (30s)',
        'Maya drafts client communication (1 min)',
      ],
      aiSupport: ['Emma', 'Sofia', 'Maya'],
      earnings: '$30-39 per mission',
      missions: '12-15 missions/month',
      totalEarnings: '$360-585/month',
      ppp: '$1,800-2,925 purchasing power',
      skillsNeeded: [
        'Can navigate Upwork',
        'Attention to detail (bug finding)',
        'Good written English',
        'No coding experience needed',
      ],
      timeCommitment: '15-20 hours/week',
    },
    {
      title: 'Specifier',
      subtitle: 'Write Specs + Manage Clients',
      icon: '📋',
      emoji: '📝',
      color: '#1EE5B8',
      whatYouDo: [
        'Review specs written by Inna (30 min)',
        'Clarify client requirements on kickoff call (30 min)',
        'Send weekly status updates to clients (15 min)',
        'Coordinate deliveries with team (30 min)',
      ],
      whatAIDoes: [
        'Inna writes complete 6-level documentation (5 min AI time)',
        'Maya drafts all client messages (1 min)',
        'Maya schedules meetings and creates agendas (30s)',
        'Inna analyzes change requests (Swap vs Add) (2 min)',
      ],
      aiSupport: ['Inna', 'Maya', 'Alexis'],
      earnings: '$58.50-78 per mission',
      missions: '8-10 missions/month',
      totalEarnings: '$468-780/month',
      ppp: '$2,340-3,900 purchasing power',
      skillsNeeded: [
        'Excellent written English',
        'Client communication skills',
        'Organized (track multiple projects)',
        'No technical background needed',
      ],
      timeCommitment: '15-20 hours/week',
    },
  ];

  const countries = [
    { name: 'Nigeria', flag: '🇳🇬', multiplier: '5-10x', example: '$900 → $4,500-9,000' },
    { name: 'Colombia', flag: '🇨🇴', multiplier: '4-6x', example: '$900 → $3,600-5,400' },
    { name: 'Pakistan', flag: '🇵🇰', multiplier: '6-8x', example: '$900 → $5,400-7,200' },
    { name: 'Kenya', flag: '🇰🇪', multiplier: '4-7x', example: '$900 → $3,600-6,300' },
    { name: 'Philippines', flag: '🇵🇭', multiplier: '3-5x', example: '$900 → $2,700-4,500' },
    { name: 'India', flag: '🇮🇳', multiplier: '5-8x', example: '$900 → $4,500-7,200' },
  ];

  return (
    <main className={styles.main}>
      {/* Hero Section */}
      <section className={styles.hero}>
        <div className={styles.heroContent}>
          <div className={styles.badge}>
            We're Hiring
          </div>

          <h1 className={styles.heroTitle}>
            Join ScopeLock: AI-Assisted Development Team
          </h1>

          <p className={styles.heroSubtitle}>
            Junior developers earn <strong>$900-1,170/month</strong> by supervising AI-generated code.
            That's <strong>$4,500-9,000 purchasing power</strong> in Nigeria, Colombia, Pakistan, and similar economies.
          </p>

          <div className={styles.heroStats}>
            <div className={styles.stat}>
              <div className={styles.statNumber}>95%</div>
              <div className={styles.statLabel}>AI does the work</div>
            </div>
            <div className={styles.stat}>
              <div className={styles.statNumber}>5%</div>
              <div className={styles.statLabel}>You supervise</div>
            </div>
            <div className={styles.stat}>
              <div className={styles.statNumber}>9h</div>
              <div className={styles.statLabel}>Per $600 mission</div>
            </div>
            <div className={styles.stat}>
              <div className={styles.statNumber}>10-12</div>
              <div className={styles.statLabel}>Missions/month</div>
            </div>
          </div>
        </div>
      </section>

      {/* Who We're Looking For */}
      <section className={styles.section}>
        <div className={styles.container}>
          <h2 className={styles.sectionTitle}>Who We're Looking For</h2>
          <p className={styles.sectionSubtitle}>
            You don't need to be a senior developer. You need to be willing to learn AI-assisted workflows.
          </p>

          <div className={styles.criteriaGrid}>
            <div className={styles.criteriaCard}>
              <div className={styles.criteriaIcon}>🌍</div>
              <h3>PPP-Advantage Countries</h3>
              <p>Nigeria, Colombia, Pakistan, Kenya, Philippines, India, Bangladesh, Egypt, Vietnam, Indonesia</p>
            </div>
            <div className={styles.criteriaCard}>
              <div className={styles.criteriaIcon}>💻</div>
              <h3>Basic Technical Skills</h3>
              <p>Can use command line, follow tutorials, willing to learn by doing. No senior experience needed.</p>
            </div>
            <div className={styles.criteriaCard}>
              <div className={styles.criteriaIcon}>⏰</div>
              <h3>15-30 Hours/Week</h3>
              <p>Flexible schedule. Work on missions when you have time. No fixed hours.</p>
            </div>
            <div className={styles.criteriaCard}>
              <div className={styles.criteriaIcon}>🗣️</div>
              <h3>Good Written English</h3>
              <p>Can read documentation, write clear messages, understand client requirements.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Available Roles */}
      <section className={styles.section} style={{ background: 'rgba(21, 26, 33, 0.4)' }}>
        <div className={styles.container}>
          <h2 className={styles.sectionTitle}>Available Roles</h2>
          <p className={styles.sectionSubtitle}>
            Choose the role that fits your skills. All roles work with AI citizens who do 95% of the work.
          </p>

          <div className={styles.rolesGrid}>
            {roles.map((role, idx) => (
              <div key={idx} className={styles.roleCard} style={{ borderColor: role.color }}>
                <div className={styles.roleHeader}>
                  <div className={styles.roleIcon}>{role.icon}</div>
                  <div>
                    <h3 className={styles.roleTitle}>{role.title}</h3>
                    <div className={styles.roleSubtitle}>{role.subtitle}</div>
                  </div>
                </div>

                <div className={styles.roleSection}>
                  <div className={styles.roleSectionHeader} style={{ color: role.color }}>
                    What You Do (5%)
                  </div>
                  <ul className={styles.roleList}>
                    {role.whatYouDo.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className={styles.roleSection}>
                  <div className={styles.roleSectionHeader} style={{ color: role.color }}>
                    What AI Does (95%)
                  </div>
                  <ul className={styles.roleList}>
                    {role.whatAIDoes.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>

                <div className={styles.roleSection}>
                  <div className={styles.roleSectionHeader} style={{ color: role.color }}>
                    Your AI Support Team
                  </div>
                  <div className={styles.aiSupportTags}>
                    {role.aiSupport.map((ai, i) => (
                      <span key={i} className={styles.aiTag} style={{ borderColor: role.color, color: role.color }}>
                        {ai}
                      </span>
                    ))}
                  </div>
                </div>

                <div className={styles.roleSection}>
                  <div className={styles.roleSectionHeader} style={{ color: role.color }}>
                    Earnings Breakdown
                  </div>
                  <div className={styles.earnings}>
                    <div className={styles.earningRow}>
                      <span>Per mission:</span>
                      <strong>{role.earnings}</strong>
                    </div>
                    <div className={styles.earningRow}>
                      <span>Missions/month:</span>
                      <strong>{role.missions}</strong>
                    </div>
                    <div className={styles.earningRow}>
                      <span>Total (nominal):</span>
                      <strong>{role.totalEarnings}</strong>
                    </div>
                    <div className={styles.earningRow} style={{ borderTop: '1px solid rgba(154, 163, 174, 0.2)', paddingTop: '8px' }}>
                      <span>PPP equivalent:</span>
                      <strong style={{ color: role.color }}>{role.ppp}</strong>
                    </div>
                  </div>
                </div>

                <div className={styles.roleSection}>
                  <div className={styles.roleSectionHeader} style={{ color: role.color }}>
                    Skills Needed
                  </div>
                  <ul className={styles.roleList}>
                    {role.skillsNeeded.map((skill, i) => (
                      <li key={i}>{skill}</li>
                    ))}
                  </ul>
                </div>

                <div className={styles.roleFooter}>
                  <div className={styles.timeCommitment}>
                    ⏰ {role.timeCommitment}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PPP Economics */}
      <section className={styles.section}>
        <div className={styles.container}>
          <h2 className={styles.sectionTitle}>Why PPP Matters</h2>
          <p className={styles.sectionSubtitle}>
            Purchasing Power Parity (PPP): Your $900 USD buys what $4,500-9,000 buys in the US
          </p>

          <div className={styles.countriesGrid}>
            {countries.map((country, idx) => (
              <div key={idx} className={styles.countryCard}>
                <div className={styles.countryFlag}>{country.flag}</div>
                <div className={styles.countryName}>{country.name}</div>
                <div className={styles.countryMultiplier}>{country.multiplier}</div>
                <div className={styles.countryExample}>{country.example}</div>
              </div>
            ))}
          </div>

          <div className={styles.pppExplanation}>
            <h3>How This Works</h3>
            <p>
              A junior developer in the US might earn $4,000-6,000/month. But rent, food, and services cost 5-10x more
              than in Nigeria, Colombia, or Pakistan.
            </p>
            <p>
              <strong>Your $900/month in Lagos or Bogotá = $4,500-9,000/month lifestyle in New York or San Francisco.</strong>
            </p>
            <p>
              ScopeLock pays in SOL (Solana) to your wallet. Convert to local currency instantly via P2P exchanges.
            </p>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className={styles.section} style={{ background: 'rgba(21, 26, 33, 0.4)' }}>
        <div className={styles.container}>
          <h2 className={styles.sectionTitle}>Your First Week</h2>
          <p className={styles.sectionSubtitle}>
            From zero to paid in 7 days
          </p>

          <div className={styles.timeline}>
            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker} style={{ background: '#FF5D5D' }}>1</div>
              <div className={styles.timelineContent}>
                <h3>Day 1-2: Onboarding</h3>
                <ul>
                  <li>Read Week 1 Critical Path (47 min)</li>
                  <li>Set up Solana wallet for payments</li>
                  <li>Get Mission Deck access from NLR</li>
                  <li>Join team Telegram chat</li>
                </ul>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker} style={{ background: '#64A8FF' }}>2</div>
              <div className={styles.timelineContent}>
                <h3>Day 3: Shadow Mission</h3>
                <ul>
                  <li>Watch NLR complete ONE mission end-to-end</li>
                  <li>Ask questions in real-time</li>
                  <li>See AI citizens in action</li>
                  <li>Take notes on workflow</li>
                </ul>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker} style={{ background: '#FFC857' }}>3</div>
              <div className={styles.timelineContent}>
                <h3>Day 4-7: First Mission (Supervised)</h3>
                <ul>
                  <li>NLR assigns simple mission ($400-500)</li>
                  <li>You complete with NLR available for questions</li>
                  <li>NLR reviews at each phase</li>
                  <li>Client accepts delivery</li>
                  <li><strong>You get paid ✅</strong></li>
                </ul>
              </div>
            </div>

            <div className={styles.timelineItem}>
              <div className={styles.timelineMarker} style={{ background: '#5CE27E' }}>4</div>
              <div className={styles.timelineContent}>
                <h3>Week 2: Independent Missions</h3>
                <ul>
                  <li>Complete 2 missions independently</li>
                  <li>NLR only reviews final delivery</li>
                  <li>You're now productive!</li>
                  <li>10-12 missions/month = $900-1,170</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className={styles.ctaSection}>
        <div className={styles.ctaContainer}>
          <h2 className={styles.ctaTitle}>Ready to Join?</h2>
          <p className={styles.ctaSubtitle}>
            Message Nicolas on Telegram to apply. Include: your country, role interest (Developer/QA/Specifier),
            and hours/week you can commit.
          </p>

          <div className={styles.ctaButtons}>
            <a
              href="https://t.me/nlr_ai"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.ctaPrimary}
            >
              Apply via Telegram →
            </a>
            <Link href="/resources" className={styles.ctaSecondary}>
              Read Resources First
            </Link>
          </div>

          <div className={styles.ctaFooter}>
            <p>
              <strong>What to say when applying:</strong>
            </p>
            <div className={styles.templateBox}>
              Hi Nicolas, I'm interested in joining ScopeLock as a [Developer/QA/Specifier].
              <br />
              <br />
              Country: [Your country]
              <br />
              Availability: [X hours/week]
              <br />
              Experience: [Brief description, or "junior developer willing to learn"]
              <br />
              <br />
              I've read the resources page and understand the AI-assisted workflow.
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
